name: lint

on:
  pull_request:

jobs:
  install_linters:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install linters
        run: npm install

  eslint:
    runs-on: ubuntu-latest
    needs: install_linters
    steps:
      - name: ESLint
        run: make -j eslint

  stylelint:
    runs-on: ubuntu-latest
    needs: install_linters
    steps:
      - name: stylelint
        run: make -j stylelint
